### ISSUE TITLE
[Question] comparison with range-v3

### ISSUE THREAD

**Issue by ameaninglessname** [IGood/IGRanges#2]
To my knowledge, [range-v3](https://github.com/ericniebler/range-v3) is aimed at a feature complete ranges library for CPP.

But it's not for Unreal, because:

> Unreal's container types (e.g. TArray<T>) do not support Ranges out of the box (yet?),

After adding "the necessary customization point objects" to range-v3, how good is that comparing to `IGRanges` ?

I don't see any "LINQ style" mentioned in range-v3 though, so this might be the competitive point of `IGRanges`?

Or could I use this two libraries together?

Thanks for this wonderful plugin!

**Comment by ameaninglessname** [comment]
I encountered some compliant errors:
![image](https://github.com/user-attachments/assets/d7db29a7-0b05-4276-bac5-d5c2d5ae27f5)

**Comment by IGood** [comment]
Hello! Thanks for showing interest in this plugin.

Sorry to see you're having compilation errors.
I've been using this with UE 5.3, Visual Studio 2022, and the MSVC v143 toolchain.
It's hard to say what's different with your environment, but I suspect that you're compiling with an older toolchain or not targeting C++20.

**Comment by IGood** [comment]
As far as compatibility with other libraries, all I can say is that there's nothing really magical about IGRanges - so if all you're looking for is a way to use `std::ranges` stuff with Unreal containers, then all you need is the code in `CustomizationPoints.h`.

Everything else in this plugin builds on top of `std::ranges` just to make common operations easier so you can write less code.
For example, `OfType<T>()` is simply a combination of `std::views::transform` & `std::views::filter`.

**Comment by ameaninglessname** [comment]
Nevermind, I was on Clang 18(Linux), UE5.5. These errors might simply come from missing standard headers then, I will check it later. Might open up a PR for 5.5.

How do you like supporting multiple engine versions? One branch for every supported engine version?

**Comment by IGood** [comment]
At this point, I haven't taken any steps to explicitly support multiple engine versions.
I've been fortunate enough that the code just works in 5.3 (where I spend most my time) and 5.4.
I'll have to test with 5.5 soon, but I don't expect any issues.

**Comment by ameaninglessname** [comment]
`_Range_closure` seems an implement detail of compiler, the one in `std` is called [range_adaptor_closure](https://en.cppreference.com/w/cpp/ranges/range_adaptor_closure) which comes with `cpp23`

**Comment by IGood** [comment]
You're probably right about `_Range_closure` - like it's a MSVC thing & then Clang will have something similar, but it wasn't standardized for C++20.
So... I don't really have a fix in the works for that because I'm not setup to build with Clang.

The other errors about missing things like [empty_view](https://en.cppreference.com/w/cpp/ranges/empty_view) are puzzling, though, because they should be part of C++20.
Perhaps they're red herrings due to the prior compilation errors.

**Comment by IGood** [comment]
IDK things about developing on Linux, but I guess it's possible that Clang 18 doesn't fully support the all C++20 features required for ranges.
Or, perhaps your standard libraries are not up to date? The internet tells me this will be something like libc++ or libstdc++ 🤷‍♂️

**Comment by RemRemRemRemRe** [comment]
Hey guys, I tried to combine this repository with `ranges-v3` recently, and made some progress [here](https://github.com/RemRemRemRe/RemRanges). Hope it helps.

I'm will to help merging those changes back to this repository if you want.

Anyway, feel free to pick or copy those changes.

**Comment by ameaninglessname** [comment]
> IDK things about developing on Linux, but I guess it's possible that Clang 18 doesn't fully support the all C++20 features required for ranges.

Your are right, and it's been fixed on ue5-main:
https://github.com/EpicGames/UnrealEngine/commit/b650926be2796dc6f5d53e143af6b532c8e28725
https://github.com/EpicGames/UnrealEngine/commit/10debcaafcd426511633129d8fb2d0dfc00f55f1

**Comment by RemRemRemRemRe** [comment]
> IDK things about developing on Linux, but I guess it's possible that Clang 18 doesn't fully support the all C++20 features required for ranges

Your are right, and it's been fixed on ue5-main:
https://github.com/EpicGames/UnrealEngine/commit/b650926be2796dc6f5d53e143af6b532c8e28725
https://github.com/EpicGames/UnrealEngine/commit/10debcaafcd426511633129d8fb2d0dfc00f55f1
